[features]
seeds = false
skip-lint = false
[programs.localnet]
messaging = "3QUUddnWRXhghTBsn6r6Q4DMN4t4y9QrNgVna2Q5BgHb"

[programs.devnet]
messaging = "3QUUddnWRXhghTBsn6r6Q4DMN4t4y9QrNgVna2Q5BgHb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/bennyhuang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
