import { Idl, ProgramAccount } from "@project-serum/anchor";
import { TypeDef } from "@project-serum/anchor/dist/cjs/program/namespace/types";
import { PublicKey } from "@solana/web3.js";

// these types are generated by Anchor
import { IDL, HypeSolanaNotepad } from "../../target/types/hype_solana_notepad";

import { useProgram } from "./use_program";

export type Note = ProgramAccount<TypeDef<typeof IDL.accounts[0], Idl>>;

const useNotesProgram = () => {
  const program = useProgram<HypeSolanaNotepad>(
    IDL,
    //Todo - there's probably a better way than hard coding
    new PublicKey("3nX4evzuDS1hg8Z3P2N8nw6jAA2yndosgPzCa8YNGB9T")
  );
  console.log("use_note_program working fine!", { program });
  return program;
};
export { useNotesProgram };
