[features]
seeds = false
skip-lint = false

[programs.localnet]
treasury = "4DCF7Nifq254YUpeKyV267vQHBR7Xuc1a16hCwg3AByg"

# FIXME what do I do with these?
# token-holding-account = "CuG7444rkeq7iDnn9nPQJ9PqLXfHcrwsschz9gDpPNRs"
# token-contract-address = "7eAd29T6m3mzUp7XRksCEbJ6uT3vnbDXGw3HtjbAZMiZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
